apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ps5-stock-checker.fullname" . }}
  labels:
    {{- include "ps5-stock-checker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ps5-stock-checker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "ps5-stock-checker.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets: 
        - name: {{ .Values.imagePullSecrets }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /ps5-stock-checker/logs
              name: ps5-stock-checker-logs
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 3
          env:
            - name: APP_VERSION
              value: "{{ .Values.image.version }}"
            {{ if .Values.cloud.config.enabled -}}
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_URL
              value: {{ .Values.cloud.config.url }}
            - name: SPRING_CLOUD_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-config-secret
                  key: username
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-config-secret
                  key: password
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: ps5-stock-checker-logs
          persistentVolumeClaim:
            claimName: ps5-stock-checker-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
