telegram:
  auth-token: test
  chat-id: test
  error-chat-id: test

ps5:
  mediamarket:
    url: "https://www.mediamarkt.es/es/product/_consola-sony-ps5-825-gb-4k-hdr-blanco-1487016.html"
  pccomponentes:
    url: "https://www.pccomponentes.com/sony-playstation-5?utm_source=460144&utm_medium=afi&utm_campaign=www.hobbyconsolas.com&awc=20981_1620633298_79914a8f4b23b69d03fd5a3903b84c96&utm_term=deeplink&utm_content=HC"
  game:
    url: "https://www.game.es/consola-playstation-5-playstation-5-183224"
  amazon:
    url: "https://www.amazon.es/dp/B08KKJ37F7/ref=sxts_spkl_2_0_19702538-81b7-4e26-8a68-a475cc66898a?pd_rd_w=Vpl1R&pf_rd_p=19702538-81b7-4e26-8a68-a475cc66898a&pf_rd_r=WR2216243PKNCHKG6NSS&pd_rd_r=e3939507-5d3b-465e-bdb9-01b9fc46ce4c&pd_rd_wg=qh0v8&qid=1620461976"

